INSERT INTO product (ID, NAME, PRICE, TYPE) VALUES(1, '신발', 39000, 1);
INSERT INTO product (ID, NAME, PRICE, TYPE) VALUES(2, '가방', 54000, 4);
INSERT INTO product (ID, NAME, PRICE, TYPE) VALUES(3, '티셔츠', 9900, 2);
INSERT INTO product (ID, NAME, PRICE, TYPE) VALUES(4, '바지', 28900, 3);
INSERT INTO product (ID, NAME, PRICE, TYPE) VALUES(5, '모자', 7990, 1);
INSERT INTO product (ID, NAME, PRICE, TYPE) VALUES(6, '반지', 1000000, 1);

INSERT INTO stock (ID, AMOUNT, SOLD_OUT) VALUES(1, 400, 'F');
INSERT INTO stock (ID, AMOUNT, SOLD_OUT) VALUES(2, 286, 'F');
INSERT INTO stock (ID, AMOUNT, SOLD_OUT) VALUES(3, 1000, 'F');
INSERT INTO stock (ID, AMOUNT, SOLD_OUT) VALUES(4, 90, 'F');
INSERT INTO stock (ID, AMOUNT, SOLD_OUT) VALUES(5, 0, 'T');
INSERT INTO stock (ID, AMOUNT, SOLD_OUT) VALUES(6, 2, 'F');

INSERT INTO productTypeInfo (ID, SUB_ID, DISCOUNT_RATIO) VALUES(2, 1, 0.7);
INSERT INTO productTypeInfo (ID, SUB_ID, DISCOUNT_RATIO) VALUES(3, 3, 1);
INSERT INTO productTypeInfo (ID, SUB_ID, DISCOUNT_RATIO) VALUES(4, 5, 1);
